// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HhB8zW8WMTkC89OKyAUeetXLTGvo3D4',
    appId: '1:524709073997:web:1d60af19dafa948032b804',
    messagingSenderId: '524709073997',
    projectId: 'nutrijourney-666',
    authDomain: 'nutrijourney-666.firebaseapp.com',
    storageBucket: 'nutrijourney-666.appspot.com',
    measurementId: 'G-8TL8K2372L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8krpszY1OaUbW2ee1Z3xkGXSpg6shQc',
    appId: '1:524709073997:android:5b599014af5b9c8b32b804',
    messagingSenderId: '524709073997',
    projectId: 'nutrijourney-666',
    storageBucket: 'nutrijourney-666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2WdpIdvQBCQx6drLJTub5AKOhcW1DhXc',
    appId: '1:524709073997:ios:864e747aef259f7232b804',
    messagingSenderId: '524709073997',
    projectId: 'nutrijourney-666',
    storageBucket: 'nutrijourney-666.appspot.com',
    iosBundleId: 'com.nutrijourney.nutrijourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2WdpIdvQBCQx6drLJTub5AKOhcW1DhXc',
    appId: '1:524709073997:ios:adbc0f291926c42732b804',
    messagingSenderId: '524709073997',
    projectId: 'nutrijourney-666',
    storageBucket: 'nutrijourney-666.appspot.com',
    iosBundleId: 'com.nutrijourney.nutrijourney.RunnerTests',
  );
}
